django_advance/conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 追加
from django.conf.urls.static import static  # 追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('crud/', include('crud.urls'))
]

# 開発環境では、メディアファイルを表示するために、
# conf/urls.pyの記述が必ず必要になります。

# 追加
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_advance/crud/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'crud'
urlpatterns = [
    path('goods_create/', login_required(views.GoodsCreate.as_view()), name='goods_create'),
    path('goods_list/', login_required(views.GoodsList.as_view()), name='goods_list'),
    path('goods_detail/<int:pk>', login_required(views.GoodsDetail.as_view()), name='goods_detail'),
    path('goods_update/<int:pk>', login_required(views.GoodsUpdate.as_view()), name='goods_update'),
    path('goods_delete/<int:pk>', login_required(views.GoodsDelete.as_view()), name='goods_delete'),
]

django_advance/crud/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.utils import timezone


class Goods(models.Model):
    name = models.CharField('商品名', unique=True, max_length=10, null=True)
    management_code = models.CharField('管理コード', unique=True, max_length=20)

    # MaxValueValidator(1000000000) 商品の価格は10億円以下しか登録不可能
    price = models.PositiveIntegerField('価格', validators=[MaxValueValidator(1000000000)])
    release_date = models.DateField('発売日', default=timezone.now)
    release_flag = models.BooleanField('発売済み', default=False)
    description = models.CharField('商品説明', max_length=100000)

    # ImageField : 画像アップロード用のフィールド
    # FileField : ファイルアップロード用のフィールド
    image = models.ImageField('商品画像', null=True, blank=True, upload_to='goods_images/')
    state_flag = models.BooleanField('運用状況', default=True)

    def __str__(self):
        return self.name

django_advance/crud/forms.py
from django import forms
from .models import Goods


class GoodsCreateForm(forms.ModelForm):
    class Meta:
        model = Goods
        fields = ('name', 'management_code', 'price', 'release_date', 'release_flag', 'description', 'image')

        # clean_フィールド名という名前をつける
        def clean_image(self):

            # フィールドの値 = self.cleaned_data.get('フィールド名')
            # 辞書のgetメソッドを使っている(この場合、デフォルト値がFalse)
            image = self.cleaned_data.get('image', False)

            # 画像がアップロードされていた場合
            if image:
                # ImageFieldとFileFieldには、.sizeという属性がある
                # 1024 = 1kb
                if image.size > 10 * 1024:
                    # clean_メソッドで、何かエラーを出したいならば
                    # raise forms.ValidationError('エラーメッセージ名')
                    raise forms.ValidationError("ファイルサイズが大きすぎます")
            # return self.cleaned_data.get('image')で取得した値
            return image

        def clean_name(self):
            name = self.cleaned_data.get('name', False)
            # NGワードが、商品名に含まれていないかチェック
            if 'NGワード' in name:
                raise forms.ValidationError("NGワードが含まれていました")
            return name


class GoodsUpdateForm(forms.ModelForm):
    class Meta:
        model = Goods
        fields = ('name', 'management_code', 'price', 'release_date', 'release_flag', 'description', 'image')

django_advance/crud/views.py
from django.views import generic
from .models import Goods
from .forms import GoodsCreateForm, GoodsUpdateForm
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import redirect


class GoodsCreate(generic.CreateView):
    form_class = GoodsCreateForm
    template_name = 'crud/goods_create.html'
    success_url = reverse_lazy('crud:goods_list')


"""
createで作成後にすぐ詳細画面にリダイレクトする場合は、
success_urlの代わりに以下のユーザー定義関数を挿入する

    def form_valid(self, form):
        goods = form.save()
        return redirect('crud:goods_detail', pk=goods.pk)
        
"""


class GoodsList(generic.ListView):
    model = Goods
    template_name = 'crud/goods_list.html'


class GoodsDetail(generic.DetailView):
    model = Goods
    template_name = 'crud/goods_detail.html'


class GoodsUpdate(generic.UpdateView):
    model = Goods
    form_class = GoodsUpdateForm
    template_name = 'crud/goods_update.html'

    def get_success_url(self):
        # リダイレクト先がデータのidを埋め込む場合（動的という）
        # このメソッドを上書きする
        goods = self.get_object()
        return reverse_lazy('crud:goods_detail', kwargs={'pk': goods.id})


class GoodsDelete(generic.DeleteView):
    model = Goods
    template_name = 'crud/goods_delete.html'
    success_url = reverse_lazy('crud:goods_list')

    # 削除処理の挙動を変更
    # DBから削除するのではなく、専用のフィールド(state_flag)をFalseにすることで、削除したことにする
    # 一覧画面からは消えるが、管理画面（admin）からは見えるようになっている
    # メソッドを上書き
    def form_valid(self, form):

        # リダイレクト先のURLを変更
        success_url = self.get_success_url()

        # モデルインスタンス.フィールド名 = 値 で、書き換えや代入ができます
        self.object.state_flag = False

        # saveメソッドで、DBのレコードの更新や作成ができる
        self.object.save()

        # self.object.delete()  # これが本来の削除処理
        return redirect(success_url)

django_advance/templates/crud/goods_create.html
{% extends 'base.html' %}
 
{% block content %}
<h2>商品作成ページ</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="save" value="作成">
</form>

{% endblock %}

django_advance/templates/crud/goods_delete.html
{% extends 'base.html' %}
 
{% block content %}

<div><a href="{% url 'crud:goods_list' %}">一覧へ戻る</a></div>

<form method="post">
    {% csrf_token %}
    <p>"{{ goods.name }}"を削除してもよろしいですか?</p>
    <input type="submit" value="削除">
</form>
 
{% endblock %}

django_advance/templates/crud/goods_detail.html
{% extends 'base.html' %}
 
{% block content %}
<a href="{% url 'crud:goods_list' %}">一覧へ戻る</a> / <a href="{% url 'crud:goods_update' goods.id %}">更新</a> / <a href="{% url 'crud:goods_delete' goods.id %}">削除</a>

<h2>商品名：{{ goods.name }}</h2>
{% if object.image %}
  <p>商品画像：</p><img class="goods-image" src="{{ object.image.url }}/">
{% endif %}
<p>管理番号：{{ goods.management_code }}</p>
<p>価格：{{ goods.price }}円</p>
<p>発売日：{{ goods.release_date }}</p>
<p>発売状況：{{ goods.release_flag }}</p>
<p>商品説明：{{ goods.description }}</p>
<p>運用状況：{{ goods.state_flag }}</p>
 
{% endblock %}

django_advance/templates/crud/goods_list.html
{% extends 'base.html' %}
 
{% block content %}
<h2>商品リスト</h2>
<div><a href="{% url 'crud:goods_create' %}">作成</a></div>
<br>

<div>
{% for goods in goods_list %}
  {% if goods.state_flag %}
    <p>{{ goods.name }}/
      <a href="{% url 'crud:goods_detail' goods.id %}">詳細</a>
      / <a href="{% url 'crud:goods_delete' goods.id %}">削除</a>
    </p>
  {% endif %}
{% endfor %}
</div>
 
{% endblock %}

django_advance/templates/crud/goods_update.html
{% extends 'base.html' %}
 
{% block content %}
<a href="{% url 'crud:goods_list' %}">一覧へ戻る</a>

<h2>商品情報更新ページ</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="save" value="更新">
</form>
 
{% endblock %}