django_ex1/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('tag/list/', views.TagListView.as_view(), name='tag_list'),
    path('article/list/', views.ArticleListView.as_view(), name='article_list'),
    path('article/detail/<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('tag/create/', views.TagCreateView.as_view(), name='tag_create'),
    path('article/create/', views.ArticleCreateView.as_view(), name='article_create'),
    path('article/update/<int:pk>/', views.ArticleUpdateView.as_view(), name='article_update'),
    path('article/delete/<int:pk>/', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('article/', views.ArticleSearchView.as_view(), name='article_search'),
    path('comment/create/<int:pk>', views.CommentCreateView.as_view(), name='comment_create'),
]

django_ex1/conf/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include  # 追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),  # 追加
]

django_ex1/blog/models.py
# Create your models here.

from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=255)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('タグ名', max_length=255)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('本文')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')

    # タグは複数紐づく。また、タグを設定しないことも可能にしている(blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='タグ')

    # adminのリストに表示する内容
    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField('名前', default='名無し', max_length=255)
    text = models.TextField('コメント内容')
    target = models.ForeignKey(
        Article, on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name='紐づく記事'
    )

    def __str__(self):
        return self.text[:50]

django_ex1/blog/forms.py
from django import forms
from .models import Tag, Article, Comment


class TagCreateForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = ('name',)


class ArticleCreateForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'text', 'category', 'tags',)


class ArticleUpdateForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'text', 'category', 'tags',)


class SearchForm(forms.Form):
    keyword = forms.CharField(label='キーワード', required=False)


class CommentCreateForm(forms.ModelForm):

    # class Meta:
    #     model = Comment
    #     fields = ('name', 'text', 'target')

    class Meta:
        model = Comment
        fields = ('name', 'text')

django_ex1/blog/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic
from django.urls import reverse_lazy
from .models import Article, Tag, Comment
from .forms import TagCreateForm, ArticleCreateForm, ArticleUpdateForm, SearchForm, CommentCreateForm
from django.db.models import Q
from django.shortcuts import redirect


class Home(generic.TemplateView):
    template_name = 'blog/home.html'


class ArticleDetailView(generic.DetailView):
    model = Article
    template_name = 'blog/article_detail.html'


class ArticleListView(generic.ListView):
    model = Article
    template_name = 'blog/article_list.html'


class TagListView(generic.ListView):
    model = Tag
    template_name = 'blog/tag_list.html'


class TagCreateView(generic.CreateView):
    model = Tag
    template_name = 'blog/tag_create.html'
    success_url = reverse_lazy('blog:tag_list')  # テンプレートで使った、urlタグみたいなもの
    form_class = TagCreateForm


class ArticleCreateView(generic.CreateView):
    model = Article
    template_name = 'blog/article_create.html'
    success_url = reverse_lazy('blog:article_list')
    form_class = ArticleCreateForm


class ArticleUpdateView(generic.CreateView):
    model = Article
    template_name = 'blog/article_update.html'
    success_url = reverse_lazy('blog:article_list')
    form_class = ArticleUpdateForm


class ArticleDeleteView(generic.DeleteView):
    model = Article
    template_name = "blog/article_delete.html"
    success_url = reverse_lazy('blog:article_list')


class ArticleSearchView(generic.ListView):
    model = Article
    template_name = 'blog/article_search.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SearchForm(self.request.GET)
        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by('created_at')
        form = SearchForm(self.request.GET)
        form.is_valid()

        keyword = form.cleaned_data.get('keyword')

        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(text__icontains=keyword)
            )

        return queryset


class CommentCreateView(generic.CreateView):
    model = Comment
    template_name = 'blog/comment_create.html'
    success_url = reverse_lazy('blog:article_list')
    form_class = CommentCreateForm

    def form_valid(self, form):

        # form.save(commit=False) データベースにはまだ保存しない
        # commit=Falseビューで、モデルのフィールドを埋めるための引数
        comment = form.save(commit=False)

        # Commentモデルの、targetフィールドをここで埋める
        # モデル名.objects.get(フィールド=値) １値だけDBから取り出すときに使うのがget
        # url内の<int:pk>は、self.kwargs['pk']で取得できる
        comment.target = Article.objects.get(pk=self.kwargs['pk'])

        # saveしないと保存されない
        comment.save()

        return redirect('blog:article_list')

django_ex1/templates/blog/article_create.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}

django_ex1/templates/blog/article_delete.html
{% extends 'base.html' %}
 
{% block content %}

<div><a href="{% url 'blog:article_list' %}">一覧へ戻る</a></div>

<form method="post">
    {% csrf_token %}
    <p>"{{ article.title }}"を削除してもよろしいですか?</p>
    <input type="submit" value="削除">
</form>
 
{% endblock %}

django_ex1/templates/blog/article_detail.html
{% extends 'base.html' %}

{% block content %}

<div>
  <h2>詳細</h2>
    <p>{{ article.title }}</p>
    <p>{{ article.text | linebreaks | urlize }}</p>
    <p>{{ article.created_at | date:'Y/m/d H:i:s' }}</p>
    <p>{{ article.category.name }}</p>

    <div>タグ：
        {% for what_tag in article.tags.all %}
            {{ what_tag.name }}
        {% endfor %}
    </div>
    <br>
</div>

<div>
    <h3>コメント欄</h3>
        <div>
            <!--  foreign keyで紐づかれたデータを全て取得する　-->
            {% for comment in article.comment_set.all %}
            <p>{{ comment.name }} : {{ comment.text | linebreaks }}</p>
            {% endfor %}
        </div>

</div>

<p>
    <a href="{% url 'blog:comment_create' article.id %}">コメント作成ページへ</a>
</p>
{% endblock %}

django_ex1/templates/blog/article_list.html
<!doctype html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Python 講座</title>
</head>
<body>

<div>

    <nav>
      <p>
          <a href={% url "blog:article_list" %}>記事一覧へ</a>
          <a href={% url "blog:tag_list" %}>タグ一覧へ</a>
      </p>
      <div id="content">
      {% block content %}{% endblock %}
      </div>
    </nav>

    <h2>記事一覧</h2>

<form action="" method="GET">
  {{ form.as_div }}
  <button type="submit">検索</button>
</form>

    {% for article in article_list %}
    <p>
        <a href="{% url 'blog:article_detail' article.pk %}">{{ article.title }} /

        {% for what_tag in article.tags.all %}
            {{ what_tag.name }}
        {% endfor %}
        </a>

        / <a href="{% url 'blog:article_delete' article.pk %}">削除</a>
    </p>
    {% endfor %}
</div>
</body>
</html>

django_ex1/templates/blog/article_update.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}

django_ex1/templates/blog/comment_create.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}

django_ex1/templates/blog/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>トップページです</h1>
</body>
</html>

django_ex1/templates/blog/tag_create.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}

django_ex1/templates/blog/tag_list.html
{% extends 'base.html' %}

{% block content %}
      <div>
        <h1>タグ一覧</h1>
            {% for tag_name in tag_list %}
                <p>{{ tag_name.name }}</p>
            {% endfor %}
      </div>

{% endblock %}