contact_form/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

]

contact_form/conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls'))
]

contact_form/contacts/urls.py
from django.urls import path
from .views import *

app_name = 'contacts'
urlpatterns = [
    path('', CorporateContactInput.as_view(), name='corporate_input'),
    path('corporate_confirm/', CorporateContactConfirm.as_view(), name='corporate_confirm'),
    path('corporate_create/', CorporateContactCreate.as_view(), name='corporate_create'),
    path('form_send_complete/', FormSendComplete.as_view(), name='form_send_complete'),
]

contact_form/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    is_received_email = models.BooleanField(verbose_name='お問い合わせメールを受け取るか', default=True)

contact_form/contacts/models.py
from django.db import models


class BaseContact(models.Model):
    """抽象モデル 継承して使うためのクラス"""
    datetime = models.DateTimeField(verbose_name='お問合せ日時', auto_now_add=True)
    content = models.TextField(verbose_name='お問合せ内容', blank=False)
    email = models.EmailField(verbose_name='メールアドレス', blank=False)

    class Meta:
        # これがあると、テーブルが作られない
        abstract = True

    def __str__(self):
        return self.content


class IndividualContact(BaseContact):
    """個人からのお問合せ"""
    fullname = models.CharField(verbose_name='氏名', blank=False, max_length=30)
    kana = models.CharField(verbose_name='フリガナ', blank=False, max_length=60)


class CorporateContact(BaseContact):
    """企業からのお問合せ"""
    corporate_name = models.CharField(verbose_name='企業名', blank=False, max_length=30)
    pic_name = models.CharField(verbose_name='担当者名', blank=False, max_length=30)
    phonenumber = models.CharField(verbose_name='電話番号', blank=False, max_length=16)

contact_form/contacts/forms.py
from django import forms
from .models import CorporateContact


class CorporateContactForm(forms.ModelForm):

    class Meta:
        model = CorporateContact
        # '__all__' とすると、全ての入力欄になる
        fields = '__all__'

contact_form/accounts/views.py
from django.shortcuts import render

# Create your views here.

contact_form/contacts/views.py
from django.views import generic
from django.urls import reverse_lazy
from .forms import CorporateContactForm
from .models import CorporateContact

from django.template.loader import get_template
from accounts.models import CustomUser
from django.shortcuts import redirect, render


# CreateViewから、データの保存処理をなくしたビューがFormView
class CorporateContactInput(generic.FormView):
    """確認画面機能の、最初の入力ページ"""
    form_class = CorporateContactForm
    template_name = 'contacts/corporate_contact_input.html'

    def form_valid(self, form):
        # 確認画面、戻るボタンを押したときに呼ばれる
        context = {
            'form': form,  # input type="hidden" で隠れていたデータが、ちゃんとはいってます
        }
        return render(
            self.request,
            'contacts/corporate_contact_input.html',
            context
        )


class CorporateContactConfirm(generic.FormView):
    form_class = CorporateContactForm

    def form_valid(self, form):
        # 入力ページ (/) で、送信を押すと呼ばれる
        context = {
            'form': form
        }
        return render(
            self.request,
            'contacts/corporate_contact_confirm.html',
            context
        )

    def form_invalid(self, form):
        context = {
            'form': form
        }
        return render(
            self.request,
            'contacts/corporate_contact_confirm.html',
            context
        )


class CorporateContactCreate(generic.CreateView):
    model = CorporateContact
    form_class = CorporateContactForm
    success_url = reverse_lazy('contacts:form_send_complete')

    def form_invalid(self, form):
        # 確認画面で、送信ボタンを押したが、入力内容が悪かった
        # 本来呼ばれないはず
        context = {
            'form': form
        }
        return render(
            self.request,
            'contacts/corporate_contact_input.html',
            context
        )

    def form_valid(self, form):
        # 確認画面で、送信を押すと呼ばれる

        # モデルフォームのsaveメソッドで、DBに保存される
        # saveメソッドは、モデルインスタンスを返す
        corporate = form.save()

        # テンプレートファイルに、辞書を渡して、メール本文の文字列を作成している
        subject = '題名'
        mail_text_template = get_template('contacts/email/corporate_message.txt')
        context = {
            'corporate': corporate,
        }
        # mail_textには、メールの本文が文字列で作られた状態
        mail_text = mail_text_template.render(context)

        # メールの送信処理
        # モデル名.objects.filter(フィールド名=値)で、絞り込むことができます
        for user in CustomUser.objects.filter(is_received_email=True):
            # 実際にメールを送る。Userモデルに定義されている、メール送信用のメソッド
            user.email_user(subject, mail_text, 'info@a.com')

        return redirect('contacts:form_send_complete')


class FormSendComplete(generic.TemplateView):
    template_name = 'contacts/form_send_complete.html'

contact_form/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Python 講座{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

contact_form/templates/contacts/corporate_contact_confirm.html
{% extends "base.html" %}
{% block title %}corporate contact form confirm{% endblock %}

{% block content %}
    <!-- 入力内容を表示している -->
    {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field.value }}
        </div>
    {% endfor %}

    <!-- 戻るボタン -->
    <form action="{% url 'contacts:corporate_input' %}" method="POST">
        {% for field in form %}
            {{ field.as_hidden }}
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">戻る</button>
    </form>
    <hr>

    <!-- 送信ボタン -->
    <form action="{% url 'contacts:corporate_create' %}" method="POST">
        {% for field in form %}
         {{ field.as_hidden }}
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
    </form>
{% endblock %}

contact_form/templates/contacts/corporate_contact_create.html
{% extends 'base.html' %}

{% block title %}お問合せ作成ページ（企業用）{% endblock %}
{% block content %}

    <form action="" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
    </form>
{% endblock %}

contact_form/templates/contacts/corporate_contact_input.html
{% extends 'base.html' %}

{% block title %}corporate contact form input{% endblock %}
{% block content %}
    <form action="{% url 'contacts:corporate_confirm' %}" method="POST">
      {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
    </form>
{% endblock %}

contact_form/templates/contacts/form_send_complete.html
{% extends 'base.html' %}

{% block title %}corporate contact form input{% endblock %}
{% block content %}
    送信完了
{% endblock %}